characters = [
    {
        "index": 0,
        "class": "sorceress",
        "ilvl-endless": 1520,
        "ilvl-aor": 1520,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 1,
        "class": "wardancer",
        "ilvl-endless": 1445,
        "ilvl-aor": 1445,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 2,
        "class": "gunslinger",
        "ilvl-endless": 1445,
        "ilvl-aor": 1445,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 3,
        "class": "reaper",
        "ilvl-endless": 1445,
        "ilvl-aor": 1445,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 4,
        "class": "artist",
        "ilvl-endless": 1490,
        "ilvl-aor": 1490,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 5,
        "class": "paladin",
        "ilvl-endless": 1475,
        "ilvl-aor": 1475,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 6,
        "class": "arcanist",
        "ilvl-endless": 1415,
        "ilvl-aor": 1415,
        "lopang": True,
        "guildDonation": False,
        "rapport": False,
    },
]
